# Author: Christopher Herzog
# Date: 2/08/2021
# Purpose: Install HAPROXY

#----- Dependency Checks -----#

- name: Check Installed Packages
  package_facts:
    manager: "auto"


#----- Install HAProxy -----#

- name: Begin Installation of HAProxy
  block:
    - name: Install HAProxy
      package:
        name: haproxy
        state: present  
  when: "'haproxy' not in ansible_facts.packages" or ansible_facts.pacakges['haproxy'].version != applications_linux.haproxy.version
  tags: install_haproxy

#----- Configure HAProxy -----#
#TODO: Create System Dependent HAProxy Server - support single deployment and/or HA deployment





#----- Start HAProxy -----#

- name: Enable HAProxy Daemon
  shell: systemctl enable haproxy
  tags: enable_haproxy

- name: Start HAProxy Daemon
  shell: systemctl start haproxy
  tags: start_haproxy
