# Author: Christopher Herzog
# Date: 2/08/2021
# Purpose: Install HAPROXY

#----- Dependency Checks -----#

- name: Check Installed Packages
  package_facts:
    manager: "auto"

- name: Begin Installation of httpd if not found
  block:
    - name: Install HTTPD
      import_role:
        name: httpd
  when:
    - "'httpd' not in ansible_facts.packages"

- name: Begin Installation of apache2 if not found
  block:
    - name: Install APACHE2
      import_role:
        name: apache2
  when:
    - "'apache2' not in ansible_facts.packages"


#----- Install HAProxy -----#

- name: Begin Installation of HAProxy
  block:
    - name: Install HAPROXY
      package:
        name: haproxy
        state: present
  when: "'haproxy' not in ansible_facts.packages" or ansible_facts.pacakges['haproxy'].version != application.haproxy.version 
